# proto-file: datacommons/config/stat_config.proto
# proto-message: PopObsSpecList
#
# IMPORTANT NOTE: The config in this file is consumed to produce the StatVar
# hierarchy.
#
# It defines Dependent PV mappings given {populationType,
# constraintProperties, measuredProperty}.  Note that we should define
# all co-occuring cprops.

## This file contains all Person + 1 cprop spec ##
## The specs are ordered by the cprop, then by the number of dpvs.

spec {
  pop_type: "Person"
  cprop: "abilityToSpeakEnglish"
  dpv: {
    prop: "age"
    val: "Years5Onwards"
  }
  dpv {
    prop: "languageSpokenAtHome"
    val: "LanguageOtherThanEnglish"
  }
  obs_props { mprop: "count" }
  vertical: "Language"
}

spec {
  pop_type: "Person"
  cprop: "age"
  dpv {
    prop: "incomeStatus"
    val: "WithIncome"
  }
  obs_props {
    mprop: "income"
  }
}

spec: {
  pop_type: "Person"
  cprop: "armedForcesStatus"
  dpv: {
    prop: "age"
    val: "Years16Onwards"
  }
  obs_props: {
    mprop: "count"
  }
  vertical: "MilitaryService"
}

## Person Income ##
# Promoted armedForcesStatus despite only v=Civilian
spec: {
  pop_type: "Person"
  cprop: "armedForcesStatus"
  dpv: {
    prop: "age"
    val: "Years18Onwards"
  }
  dpv: {
    prop: "incomeStatus"
    val: "WithIncome"
  }
  obs_props: {
    mprop: "income"
  }
  vertical: "MilitaryService"
}

spec: {
  pop_type: "Person"
  cprop: "bachelorsDegreeMajor"
  dpv: {
    prop: "educationalAttainment"
    val: "BachelorsDegreeOrHigher"
  }
  dpv: {
    prop: "age"
    val: "Years25Onwards"
  }
  obs_props: {
    mprop: "count"
  }
}

spec {
  pop_type: "Person"
  cprop: "birthEventStatus"
  dpv {
    prop: "gender"
    val: "Female"
  }
  obs_props {
    mprop: "count"
  }
}

spec {
  pop_type: "Person"
  cprop: "commuteMode"
  dpv {
    prop: "age"
    val: "Years16Onwards"
  }
  dpv {
    prop: "employment"
    val: "USC_EmployedAndWorking"
  }
  dpv {
    prop: "employmentStatus"
    val: "BLS_InLaborForce"
  }
  obs_props {
    mprop: "count"
  }
  vertical: "Commute"
}

spec {
  pop_type: "Person"
  cprop: "commuteTime"
  dpv {
    prop: "age"
    val: "Years16Onwards"
  }
  dpv {
    prop: "employment"
    val: "USC_EmployedAndWorking"
  }
  dpv {
    prop: "employmentStatus"
    val: "BLS_InLaborForce"
  }
  dpv {
    prop: "placeOfWork"
    val: "OutsideOfHome"
  }
  obs_props {
    mprop: "count"
  }
  obs_props {
    mprop: "commuteTime"
  }
  vertical: "Commute"
}

# Detailed Level of School for 3+YO enrolled in school
spec: {
  pop_type: "Person"
  cprop: "detailedLevelOfSchool"
  dpv: {
    prop: "schoolEnrollment"
    val: "EnrolledInSchool"
  }
  dpv: {
    prop: "age"
    val: "Years3Onwards"
  }
  obs_props: {
    mprop: "count"
  }
  vertical: "Education"
}

spec: {
  pop_type: "Person"
  cprop: "economicSector"
  dpv: {
    prop: "employment"
    val: "Employed"
  }
  obs_props: {
    mprop: "count"
  }
  vertical: "Employment"
}

spec: {
  pop_type: "Person"
  cprop: "educationalAttainment"
  dpv: {
    prop: "age"
    val: "Years25Onwards"
  }
  obs_props: {
    mprop: "count"
  }
  vertical: "Education"
}

spec: {
  pop_type: "Person"
  cprop: "educationalAttainment"
  dpv: {
    prop: "age"
    val: "Years25Onwards"
  }
  dpv: {
    prop: "incomeStatus"
    val: "WithIncome"
  }
  obs_props: {
    mprop: "income"
  }
  vertical: "Education"
}

spec {
  pop_type: "Person"
  cprop: "employmentStatus"
  dpv {
    prop: "age"
    val: "Years14Onwards"
  }
  obs_props {
    mprop: "count"
  }
  vertical: "Economy"
}



spec: {
  pop_type: "Person"
  cprop: "gender"
  dpv: {
    prop: "age"
    val: "Years15Onwards"
  }
  dpv: {
    prop: "incomeStatus"
    val: "WithIncome"
  }
  obs_props: {
    mprop: "income"
  }
  vertical: "Demographics"
}

spec {
  pop_type: "Person"
  cprop: "hasOccupation"
  dpv {
    prop: "age"
    val: "Years16Onwards"
  }
  dpv {
    prop: "armedForcesStatus"
    val: "Civilian"
  }
  dpv {
    prop: "employmentStatus"
    val: "BLS_Employed"
  }
  dpv {
    prop: "incomeStatus"
    val: "WithEarnings"
  }
  dpv {
    prop: "workStatus"
    val: "USC_FullTimeYearRoundWorker"
  }
  obs_props {
    mprop: "income"
  }
}

## Person percent ##
spec: {
  pop_type: "Person"
  cprop: "healthBehavior"
  dpv: {
    prop: "age"
    val: "Years18Onwards"
  }
  obs_props: {
    mprop: "percent"
  }
  vertical: "Health"
}

spec: {
  pop_type: "Person"
  cprop: "healthInsurance"
  dpv: {
    prop: "institutionalization"
    val: "USC_NonInstitutionalized"
  }
  dpv: {
    prop: "armedForcesStatus"
    val: "Civilian"
  }
  obs_props: {
    mprop: "count"
  }
}

spec: {
  pop_type: "Person"
  cprop: "healthOutcome"
  dpv: {
    prop: "age"
    val: "Years18Onwards"
  }
  obs_props: {
    mprop: "percent"
  }
  vertical: "Health"
}

spec: {
  pop_type: "Person"
  cprop: "healthPrevention"
  dpv: {
    prop: "age"
    val: "Years18Onwards"
  }
  obs_props: {
    mprop: "percent"
  }
  vertical: "Health"
}

# https://data.census.gov/cedsci/table?tid=ACSDT1Y2019.B27015
spec: {
  pop_type: "Person"
  cprop: "householdIncome"
  dpv: {
    prop: "armedForcesStatus"
    val: "Civilian"
  }
  dpv: {
    prop: "residenceType"
    val: "Household"
  }
  obs_props: {
    mprop: "count"
  }
}

spec: {
  pop_type: "Person"
  cprop: "income"
  dpv: {
    prop: "age"
    val: "Years15Onwards"
  }
  dpv: {
    prop: "incomeStatus"
    val: "WithIncome"
  }
  obs_props: { mprop: "count" }
  vertical: "Demographics"
}

spec {
  pop_type: "Person"
  obs_props { mprop: "count" }
  cprop: "languageSpokenAtHome"
  dpv: {
    prop: "age"
    val: "Years5Onwards"
  }
  vertical: "Language"
}

## Census B14001
## Universe: Population 3 Years and Over
# MISSING NotEnrolledInSchool counts, so schoolEnrollment becomes a dpv here
spec: {
  pop_type: "Person"
  cprop: "levelOfSchool"
  dpv: {
    prop: "schoolEnrollment"
    val: "EnrolledInSchool"
  }
  dpv: {
    prop: "age"
    val: "Years3Onwards"
  }
  obs_props: {
    mprop: "count"
  }
  vertical: "Education"
}

spec: {
  pop_type: "Person"
  cprop: "maritalStatus"
  dpv: {
    prop: "age"
    val: "Years15Onwards"
  }
  obs_props: { mprop: "count" }
  vertical: "Demographics"
}

spec {
  pop_type: "Person"
  cprop: "naics"
  dpv {
    prop: "age"
    val: "Years16Onwards"
  }
  dpv {
    prop: "armedForcesStatus"
    val: "Civilian"
  }
  dpv {
    prop: "employmentStatus"
    val: "BLS_Employed"
  }
  dpv {
    prop: "incomeStatus"
    val: "WithEarnings"
  }
  obs_props {
    mprop: "income"
  }
}

spec: {
  pop_type: "Person"
  cprop: "nativity"
  dpv: {
    prop: "age"
    val: "Years5Onwards"
  }
  obs_props: { mprop: "count" }
  vertical: "ImmigrationAndCitizenship"
}

spec: {
  pop_type: "Person"
  cprop: "occupation"
  dpv {
    prop: "age"
    val: "Years16Onwards"
  }
  dpv {
    prop: "armedForcesStatus"
    val: "Civilian"
  }
  dpv {
    prop: "employmentStatus"
    val: "BLS_Employed"
  }
  obs_props: { mprop: "count" }
}

spec: {
  pop_type: "Person"
  cprop: "periodOfMilitaryService"
  dpv {
    prop: "age"
    val: "Years18Onwards"
  }
  dpv {
    prop: "armedForcesStatus"
    val: "Civilian"
  }
  dpv {
    prop: "veteranStatus"
    val: "Veteran"
  }
  obs_props: { mprop: "count" }
  vertical: "MilitaryService"
}

spec: {
  pop_type: "Person"
  cprop: "placeOfBirth"
  dpv: {
    prop: "age"
    val: "Years15Onwards"
  }
  dpv: {
    prop: "incomeStatus"
    val: "WithIncome"
  }
  obs_props: {
    mprop: "income"
  }
  vertical: "Demographics"
  vertical: "ImmigrationAndCitizenship"
}

spec {
  pop_type: "Person"
  cprop: "placeOfWork"
  dpv {
    prop: "age"
    val: "Years16Onwards"
  }
  dpv {
    prop: "employment"
    val: "USC_EmployedAndWorking"
  }
  dpv {
    prop: "employmentStatus"
    val: "BLS_InLaborForce"
  }
  obs_props {
    mprop: "count"
  }
  vertical: "Commute"
}

## Table B14007
## Universe: Population 3 Years and Over
# 3+YO Not/Enrolled in school
spec: {
  pop_type: "Person"
  cprop: "schoolEnrollment"
  dpv: {
    prop: "age"
    val: "Years3Onwards"
  }
  obs_props: {
    mprop: "count"
  }
  vertical: "Education"
}

spec {
  pop_type: "Person"
  cprop: "usualHoursWorked"
  dpv {
    prop: "age"
    val: "16To64Years"
  }
  dpv {
    prop: "workStatus"
    val: "WorkedInThePast12Months"
  }
  obs_props {
    mprop: "count"
  }
}

spec {
  pop_type: "Person"
  cprop: "workPeriod"
  dpv {
    prop: "age"
    val: "16To64Years"
  }
  dpv {
    prop: "workStatus"
    val: "WorkedInThePast12Months"
  }
  obs_props {
    mprop: "count"
  }
}

spec {
  pop_type: "Person"
  cprop: "workPeriod"
  dpv {
    prop: "workerClassification"
    val: "MarginalWorker"
  }
  dpv {
    prop: "workerStatus"
    val: "Worker"
  }
  obs_props {
    mprop: "count"
  }
}

spec {
  pop_type: "Person"
  cprop: "workStatus"
  dpv {
    prop: "age"
    val: "16To64Years"
  }
  obs_props {
    mprop: "count"
  }
}

spec {
  pop_type: "Person"
  cprop: "workerClassification"
  dpv {
    prop: "workerStatus"
    val: "Worker"
  }
  obs_props {
    mprop: "count"
  }
}
